vars:
  - n_games: 10
  - player_classes: random,deep_learning
  - log_directory_path: data/game_logs/
  - params_path: params.yaml
  - preprocessed_h5_path: data/preprocessed_game_logs.h5
  - collect_data_metrics_path: results/metrics/collect_data.json
  - evaluate_deep_learning_player_metrics_path: results/metrics/evaluate_deep_learning_player.json
  - model_folder_path: results/models/

stages:
  collect_data:
    cmd: >
      python scripts/run_competition_between_players.py
      --n_games ${n_games}
      --player_classes ${player_classes}
      --log_directory_path ${log_directory_path}
      --metrics_json_path ${collect_data_metrics_path}
    deps:
      - scripts/run_competition_between_players.py
    outs:
      - ${log_directory_path}
    metrics:
      - ${collect_data_metrics_path}:
          cache: false
  preprocess_data:
    cmd: >
      python scripts/preprocess_game_logs.py
      --game_logs_folder_path ${log_directory_path}
      --output_h5_path ${preprocessed_h5_path}
    deps:
      - scripts/preprocess_game_logs.py
      - ${log_directory_path}
    outs:
      - ${preprocessed_h5_path}
  train_deep_learning_scorer:
    cmd: >
      python scripts/train_deep_learning_scorer.py
      --params_path ${params_path}
      --preprocessed_game_logs_path ${preprocessed_h5_path}
      --model_folder_path ${model_folder_path}
      --model_file_name deep_learning_scorer
    deps:
      - scripts/train_deep_learning_scorer.py
      - ${preprocessed_h5_path}
    params:
      - ${params_path}:
          - deep_learning_scorer
    outs:
      - ${model_folder_path}/deep_learning_scorer.ckpt
  evaluate_deep_learning_player:
    cmd: >
      python scripts/run_competition_between_players.py
      --n_games ${n_games}
      --player_classes ${player_classes}
      --metrics_json_path ${evaluate_deep_learning_player_metrics_path}
      --deep_learning_scorer_path ${model_folder_path}/deep_learning_scorer.ckpt
    deps:
      - scripts/run_competition_between_players.py
      - ${model_folder_path}/deep_learning_scorer.ckpt
    metrics:
      - ${evaluate_deep_learning_player_metrics_path}:
          cache: false
