vars:
  - n_games: 10
  - player_classes: random,random
  - log_directory_path: data/game_logs/
  - collect_data_metrics_path: metrics/collect_data.json
  - preprocessed_h5_path: data/preprocessed_game_logs.h5

stages:
  collect_data:
    cmd: >
      python scripts/run_competition_between_players.py
      --n_games ${n_games}
      --player_classes ${player_classes}
      --log_directory_path ${log_directory_path}
      --metrics_json_path ${collect_data_metrics_path}
    deps:
      - scripts/run_competition_between_players.py
    outs:
      - ${log_directory_path}
    metrics:
      - ${collect_data_metrics_path}:
          cache: false
  preprocess_data:
    cmd: >
      python scripts/preprocess_game_logs.py
      --game_logs_folder_path ${log_directory_path}
      --output_h5_path ${preprocessed_h5_path}
    deps:
      - scripts/preprocess_game_logs.py
      - ${log_directory_path}
    outs:
      - ${preprocessed_h5_path}
