deep_learning_scorer:
  hyper_parameters:
    n_players: 2
    player_dim: 8
    max_n_cards: 120
    card_dim: 34
    action_general_dim: 31
    final_common_dim: 32
    transformer_n_layers: 2
    transformer_n_heads: 4
    dropout: 0.1
  training:
    random_split:
      training_size: 0.8
      validation_size: 0.2
    batch_size: 100
    n_epochs: 1000
    model_checkpoint:
      monitor: validation_loss
      mode: min
      save_top_k: 1
      verbose: false
    early_stopping:
      monitor: validation_loss
      mode: min
      patience: 10
      verbose: false
